#!/bin/bash
# Prepares the iOS project for one app: ./tool/ios_setup.sh client|pro
# The ios/ folder is generated by Flutter on the build machine (macOS), then given the
# app's name, id, icon, permissions and minimum iOS version.
set -euo pipefail
APP="$1"
cd "$(dirname "$0")/.."

if [ ! -d ios ]; then
  flutter create --platforms=ios --org com.promarket --project-name zariz . >/dev/null
fi
rm -f test/widget_test.dart

if [ "$APP" = "pro" ]; then BID=com.promarket.pro; NAME="זריז מקצוענים"; else BID=com.promarket.client; NAME="זריז"; fi
PL=ios/Runner/Info.plist

plutil -replace CFBundleDisplayName -string "$NAME" "$PL"
plutil -replace CFBundleName -string "$NAME" "$PL"
plutil -replace CFBundleDevelopmentRegion -string "he" "$PL"
plutil -replace CFBundleLocalizations -json '["he"]' "$PL"
plutil -replace ITSAppUsesNonExemptEncryption -bool NO "$PL"
plutil -replace NSCameraUsageDescription -string "לצלם את התקלה או מסמך לאישור" "$PL"
plutil -replace NSPhotoLibraryUsageDescription -string "לצרף תמונה מהגלריה לקריאה" "$PL"
if [ "$APP" = "pro" ]; then
  plutil -replace NSLocationWhenInUseUsageDescription -string "כדי להציג קריאות באזור שלכם ולהראות ללקוח שאתם בדרך" "$PL"
  plutil -replace NSLocationAlwaysAndWhenInUseUsageDescription -string "כשאתם זמינים או בדרך ללקוח, המיקום משותף גם כשהאפליקציה ברקע" "$PL"
  plutil -replace UIBackgroundModes -json '["location"]' "$PL"
else
  plutil -replace NSLocationWhenInUseUsageDescription -string "כדי למלא את הכתובת שלכם בקריאה" "$PL"
  plutil -replace NSLocationAlwaysAndWhenInUseUsageDescription -string "כדי למלא את הכתובת שלכם בקריאה" "$PL"
fi
# Plain http is allowed only while an http:// address is still in the list.
if [[ "${SERVER_URL:-}${FALLBACK_URL:-}" == *"http://"* ]]; then
  plutil -replace NSAppTransportSecurity -json '{"NSAllowsArbitraryLoads":true}' "$PL"
else
  plutil -remove NSAppTransportSecurity "$PL" 2>/dev/null || true
fi

PBX=ios/Runner.xcodeproj/project.pbxproj
sed -i '' -E "s/PRODUCT_BUNDLE_IDENTIFIER = com\.promarket\.zariz;/PRODUCT_BUNDLE_IDENTIFIER = $BID;/g" "$PBX"
sed -i '' -E "s/IPHONEOS_DEPLOYMENT_TARGET = [0-9.]+;/IPHONEOS_DEPLOYMENT_TARGET = 15.0;/g" "$PBX"
if [ -n "${APPLE_TEAM_ID:-}" ]; then
  sed -i '' -E "s/(PRODUCT_BUNDLE_IDENTIFIER = $BID;)/\1 DEVELOPMENT_TEAM = $APPLE_TEAM_ID; CODE_SIGN_STYLE = Automatic;/g" "$PBX"
fi
if [ -f ios/Podfile ]; then
  sed -i '' -E "s/^#? *platform :ios, .*/platform :ios, '15.0'/" ios/Podfile
fi

# Notifications also show while the app is open (flutter_local_notifications needs the
# app delegate to be the notification center's delegate).
AD=ios/Runner/AppDelegate.swift
if [ -f "$AD" ] && ! grep -q "UNUserNotificationCenter" "$AD"; then
  perl -0pi -e 's/import UIKit\n/import UIKit\nimport UserNotifications\n/; s/(\n\s*)(return super\.application\(application, didFinishLaunchingWithOptions)/$1UNUserNotificationCenter.current().delegate = self as? UNUserNotificationCenterDelegate$1$2/' "$AD"
  grep -q "UNUserNotificationCenter" "$AD" && echo "AppDelegate: notifications in the foreground on" || echo "::warning::AppDelegate not patched (template changed)"
fi

# App icon: one 1024px image (Xcode makes the other sizes)
SET=ios/Runner/Assets.xcassets/AppIcon.appiconset
rm -rf "$SET" && mkdir -p "$SET"
cp "ios-assets/icon-$APP-1024.png" "$SET/icon-1024.png"
cat > "$SET/Contents.json" <<'EOF'
{
  "images" : [ { "filename" : "icon-1024.png", "idiom" : "universal", "platform" : "ios", "size" : "1024x1024" } ],
  "info" : { "author" : "xcode", "version" : 1 }
}
EOF
echo "iOS project ready: $NAME ($BID)"
